### ISSUE TITLE
which version of keras and tensorflow

### ISSUE THREAD

**Issue by SeekPoint** [vendi12/tableQA#1]
ali-186590cc37a5:tableQA yike.ke$ python table_rnn.py 
Using TensorFlow backend.
RNN / Embed / Sent / Query = <class 'keras.layers.recurrent.LSTM'>, 20, 100, 100
-
Vocab size: 88 unique words
Story max length: 126 words
Query max length: 11 words
Number of training samples: 6204
Number of test samples: 8947
-
Here's what a "story" tuple looks like (input, query, answer):
([u'Row1', u'NUTS2', u'AT31', u'Row1', u'LAU2_CODE', u'41015', u'Row1', u'LAU2_NAME', u'Allhaming', u'Row1', u'YEAR', u'2006', u'Row1', u'INTERNAL_MIG_IMMIGRATION', u'8', u'Row1', u'INTERNATIONAL_MIG_IMMIGRATION', u'7', u'Row1', u'IMMIGRATION_TOTAL', u'10240', u'Row1', u'INTERNAL_MIG_EMIGRATION', u'7', u'Row1', u'INTERNATIONAL_MIG_EMIGRATION', u'7', u'Row1', u'EMIGRATION_TOTAL', u'3', u'Row2', u'NUTS2', u'AT31', u'Row2', u'LAU2_CODE', u'41013', u'Row2', u'LAU2_NAME', u'Neuhofen_an_der_Krems', u'Row2', u'YEAR', u'2005', u'Row2', u'INTERNAL_MIG_IMMIGRATION', u'15', u'Row2', u'INTERNATIONAL_MIG_IMMIGRATION', u'6', u'Row2', u'IMMIGRATION_TOTAL', u'8', u'Row2', u'INTERNAL_MIG_EMIGRATION', u'6', u'Row2', u'INTERNATIONAL_MIG_EMIGRATION', u'3', u'Row2', u'EMIGRATION_TOTAL', u'3', u'Row3', u'NUTS2', u'AT31', u'Row3', u'LAU2_CODE', u'41011', u'Row3', u'LAU2_NAME', u'Munderfing', u'Row3', u'YEAR', u'2004', u'Row3', u'INTERNAL_MIG_IMMIGRATION', u'10', u'Row3', u'INTERNATIONAL_MIG_IMMIGRATION', u'5', u'Row3', u'IMMIGRATION_TOTAL', u'9', u'Row3', u'INTERNAL_MIG_EMIGRATION', u'2', u'Row3', u'INTERNATIONAL_MIG_EMIGRATION', u'8', u'Row3', u'EMIGRATION_TOTAL', u'2', u'Row4', u'NUTS2', u'AT31', u'Row4', u'LAU2_CODE', u'41008', u'Row4', u'LAU2_NAME', u'Bad_Goisern_am_Hallst', u'\xe4', u'ttersee', u'Row4', u'YEAR', u'2005', u'Row4', u'INTERNAL_MIG_IMMIGRATION', u'9', u'Row4', u'INTERNATIONAL_MIG_IMMIGRATION', u'10', u'Row4', u'IMMIGRATION_TOTAL', u'1', u'Row4', u'INTERNAL_MIG_EMIGRATION', u'13', u'Row4', u'INTERNATIONAL_MIG_EMIGRATION', u'12', u'Row4', u'EMIGRATION_TOTAL', u'7'], [u'What', u'is', u'the', u'INTERNAL_MIG_IMMIGRATION', u'for', u'Bad_Goisern_am_Hallst', u'\xe4', u'ttersee', u'?'], u'9')
-
Vectorizing the word sequences...
vocab = [u'0', u'1', u'10', u'10240', u'11', u'12', u'13', u'14', u'15', u'16', u'2', u'2002', u'2003', u'2004', u'2005', u'2006', u'2007', u'2008', u'2009', u'2010', u'2011', u'2012', u'2013', u'2014', u'2015', u'3', u'4', u'4098', u'41001', u'41002', u'41003', u'41004', u'41005', u'41006', u'41007', u'41008', u'41009', u'41010', u'41011', u'41012', u'41013', u'41014', u'41015', u'5', u'6', u'7', u'8', u'9', u'?', u'AT31', u'Allhaming', u'Arbing', u'Bad_Goisern_am_Hallst', u'Bad_Goisern_am_Hallst\xe4ttersee', u'Burgkirchen', u'Desselbrunn', u'EMIGRATION_TOTAL', u'Geretsberg', u'Grieskirchen', u'Helfenberg', u'IMMIGRATION_TOTAL', u'INTERNAL_MIG_EMIGRATION', u'INTERNAL_MIG_IMMIGRATION', u'INTERNATIONAL_MIG_EMIGRATION', u'INTERNATIONAL_MIG_IMMIGRATION', u'LAU2_CODE', u'LAU2_NAME', u'Munderfing', u'NUTS2', u'Neuhofen_an_der_Krems', u'Obernberg_am_Inn', u'Raab', u'Row1', u'Row2', u'Row3', u'Row4', u'Suben', u'Traun', u'Waizenkirchen', u'What', u'YEAR', u'for', u'in', u'is', u'the', u'ttersee', u'\xe4']
X.shape = (6204, 126)
Xq.shape = (6204, 11)
Y.shape = (6204, 88)
story_maxlen, query_maxlen = 126, 11
Build model...
Traceback (most recent call last):
  File "table_rnn.py", line 132, in <module>
    train_rnn(train, test)
  File "table_rnn.py", line 99, in train_rnn
    qrnn.add(RNN(EMBED_HIDDEN_SIZE, return_sequences=False))
  File "/Library/Python/2.7/site-packages/keras/models.py", line 463, in add
    output_tensor = layer(self.outputs[0])
  File "/Library/Python/2.7/site-packages/keras/layers/recurrent.py", line 257, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/Library/Python/2.7/site-packages/keras/engine/topology.py", line 551, in __call__
    self.build(input_shapes[0])
  File "/Library/Python/2.7/site-packages/keras/layers/recurrent.py", line 994, in build
    K.set_value(self.bias, bias_value)
  File "/Library/Python/2.7/site-packages/keras/backend/tensorflow_backend.py", line 2000, in set_value
    get_session().run(assign_op, feed_dict={assign_placeholder: value})
  File "/Library/Python/2.7/site-packages/keras/backend/tensorflow_backend.py", line 155, in get_session
    _initialize_variables()
  File "/Library/Python/2.7/site-packages/keras/backend/tensorflow_backend.py", line 300, in _initialize_variables
    variables = tf.global_variables()
AttributeError: 'module' object has no attribute 'global_variables'
ali-186590cc37a5:tableQA yike.ke$

**Comment by svakulenk0** [comment]
Keras==2.0.6 tensorflow==1.1.0

**Comment by svakulenk0** [comment]
let me know if that helped!

**Comment by svakulenk0** [comment]
ah ok keras is running Theano backend here: Theano==0.9.0 you can switch in keras settings

**Comment by SeekPoint** [comment]
On training now....
